name: Run build

on:
  workflow_dispatch:
    inputs:
      os_version:
        description: 'Select OS'
        required: true
        default: '["ubuntu-latest"]'
        type: choice
        options:
          - '["ubuntu-latest"]'
          - '["macos-latest"]'
          - '["ubuntu-latest","macos-latest"]'
          # - '["windows-latest"]'

jobs:
  test:
    name: Build on ${{ matrix.os }}
    strategy:
      matrix:
        os: ${{ fromJSON(inputs.os_version) }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install dependencies
        run: |
          # sudo apt update -y
          # sudo apt install -y build-essential gcc
          brew install cmake
          brew install ninja
          brew install meson
          brew install nasm
          brew install libpng
          brew install jpeg

      - name: Clone libavif repo
        run: |
          git clone --depth 1 https://github.com/AOMediaCodec/libavif.git
          ls -la

      - name: Restore cached libs
        id: cache-libs-restore
        uses: actions/cache/restore@v3
        with:
          path: |
            libavif/ext/libyuv
            libavif/ext/aom
            libavif/ext/dav1d
          key: ${{ runner.os }}-libs

      - name: Build libyuv
        if: steps.cache-libs-restore.outputs.cache-hit != 'true'
        working-directory: ./libavif/ext/
        run: |
          ./libyuv.cmd

      - name: Build aom
        if: steps.cache-libs-restore.outputs.cache-hit != 'true'
        working-directory: ./libavif/ext/
        run: |
          ./aom.cmd

      - name: Build dav1d
        if: steps.cache-libs-restore.outputs.cache-hit != 'true'
        working-directory: ./libavif/ext/
        run: |
          ./dav1d.cmd

      - name: Save libs to cache
        id: cache-libs-save
      - uses: actions/cache/save@v3
        with:
          path: |
            libavif/ext/libyuv
            libavif/ext/aom
            libavif/ext/dav1d
          key: ${{ steps.cache-libs-restore.outputs.cache-primary-key }}

      - name: Build libavif binaries
        run: |
          cd ./libavif/
          mkdir build
          cd build
          cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DAVIF_CODEC_AOM=ON -DAVIF_LOCAL_AOM=ON -DAVIF_CODEC_AOM_DECODE=ON -DAVIF_CODEC_AOM_ENCODE=ON -DAVIF_CODEC_DAV1D=ON -DAVIF_LOCAL_DAV1D=ON -DAVIF_LOCAL_LIBYUV=ON -DAVIF_BUILD_APPS=ON ..
          ninja
          ls -la

      - name: Test avifenc
        run: |
          ./libavif/build/avifenc --version

      - name: Test avifdec
        run: |
          ./libavif/build/avifdec --version

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-avif-binaries
          path: |
            ./libavif/build/avifenc
            ./libavif/build/avifdec

      # - if: ${{ matrix.os == 'ubuntu-latest' }}
      #   run: |
      #     echo ""

      # - if: ${{ matrix.os == 'macos-latest' }}
      #   run: |
      #     echo ""

      # - if: ${{ matrix.os == 'windows-latest' }}
      #   run: |
      #     echo ""
